apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

images:
  - name: radhaneelam/coit-frontend
    newTag: v1.0.0
    

commonLabels:
  environment: production 

nameSuffix: -production
replicas:
  - name: coit-frontend
    count: 4

namespace: production
