apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./coit-frontend-deployment.yaml
- ./service-coit-frontend-lb.yaml

images:
- name: radhaneelam/coit-frontend
  newTag: v1.0


commonLabels:
  app: coit-frontend
  managed-by: kustomize

